strict-sigcheck = false

[AliExpress]
enables = true
brand = "quantro100"
apkmirror-dlurl = "https://www.apkmirror.com/apk/alibaba-mobile/aliexpress-shopping-app/"
uptodown-dlurl = "https://aliexpress.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["AliExpress"]

[AliExpress.patches]
"github:Quantro100/Morphe-patches" = []

[Amazon-Shopping]
enabled = true
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
uptodown-dlurl = "https://amazon-shopping.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Amazon"]

[Amazon-Shopping.patches]
"github:rushiranpise/morphe-patches" = []

[Finch]
enabled = true
brand = "hooman"
apkmirror-dlurl = "https://www.apkmirror.com/apk/finch-care-inc/finch-self-care-widget-pet/"
uptodown-dlurl = "https://finch.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Finch"]

[Finch.patches]
"github:arandomhooman/hoomans-morphe-patches" = []

[GitHub]
enabled = true
brand = "hoodles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2/"
uptodown-dlurl = "https://github-android.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["GitHub"]

[GitHub.patches]
"github:hoo-dles/morphe-patches" = []

[InShot]
enabled = true
brand = "hooman"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc/inshot-video-editor-photo-editor/"
uptodown-dlurl = "https://inshot-editor.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["InShot"]

[InShot.patches]
"github:arandomhooman/hoomans-morphe-patches" = []

[Instagram]
enabled = true
brand = "piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
patcher-args = "-e 'Theme' -Oamoled=true"
changelog-keywords = ["Instagram"]

[Instagram.patches]
"github:crimera/piko" = []

[Letterboxd]
enabled = true
brand = "devanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd/letterboxd/"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Letterboxd"]

[Letterboxd.patches]
"github:RookieEnough/De-Vanced" = []

[Mimo]
enabled = true
brand = "hoodles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mimohello-gmbh/mimo-learn-to-code/"
uptodown-dlurl = "https://mimo.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Mimo"]

[Mimo.patches]
"github:hoo-dles/morphe-patches" = []

[Pinterest]
enabled = true
brand = "binarymend"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration/"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Pinterest"]

[Pinterest.patches]
"github:binarymend/morphe-patches" = []

[TikTok]
enabled = true
brand = "devanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Tiktok"]

[TikTok.patches]
"github:RookieEnough/De-Vanced" = []
